name: service-ci

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install uv
          uv pip install --system .[dev]
      - name: Ruff
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install uv
          uv pip install --system .[dev]
      - name: Pytest
        run: pytest

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install pip-audit
      - name: Pip audit
        run: pip-audit -r requirements.txt || true # allow demo deps

  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: |
          docker build -t ghcr.io/example/${{ inputs.service-name }}:${{ github.sha }} .
          docker tag ghcr.io/example/${{ inputs.service-name }}:${{ github.sha }} ghcr.io/example/${{ inputs.service-name }}:latest-dev
      - name: Login to GHCR
        if: secrets.GHCR_TOKEN != ''
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push images
        if: secrets.GHCR_TOKEN != ''
        run: |
          docker push ghcr.io/example/${{ inputs.service-name }}:${{ github.sha }}
          docker push ghcr.io/example/${{ inputs.service-name }}:latest-dev
